Algoritmo "antecessor"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Lê um número e calcula o seu antecessor
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 12/04/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro
antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número: ")
   leia(numero)
   antecessor <- numero - 1
   escreva("O antecessor é: ", antecessor)

Fimalgoritmo