Algoritmo "area_circulo"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Lê o valor do raio de um circulo e calcula sua área.
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 14/04/2026
Var
// Seção de Declarações das variáveis 
raio: real
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor do raio: ")
   leia(raio)
   area <- pi * raio * 2
   escreva("A área do circulo é: ", area)

Fimalgoritmo