Algoritmo "area quadrado"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Lê o valor do lado de um quadrado e calcula sua área.
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 14/04/2026
Var
// Seção de Declarações das variáveis 
lado: real
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor do lado: ")
   leia(lado)
   area <- lado * lado
   escreva("A área do quadrado é: ", area)

Fimalgoritmo