Algoritmo "conversor metros para centimetros"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Converte metros para centimetros
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 15/04/2026
Var
// Seção de Declarações das variáveis 
metros, centimetros: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a quantidade de metros: ")
   leia(metros)
   
   centimetros <- metros * 100
   
   escreva("O equivalente em centimetros é:", centimetros)

Fimalgoritmo