Algoritmo "divisao"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Solicita dois números, divide e exibe o resultado
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 12/04/2026
Var
// Seção de Declarações das variáveis 
dividendo: inteiro
divisor: inteiro
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o dividendo: ")
   leia(dividendo)
   escreva("Digite o divisor: ")
   leia(divisor)
   resultado <- dividendo / divisor
   escreva("O resultado da divisão é: ", resultado)

Fimalgoritmo