Algoritmo "dobro da area do quadrado"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Calcula a área de um quadrado e mostra o dobro da área
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 15/04/2026
Var
// Seção de Declarações das variáveis 
lado, dobro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor do lado: ")
   leia(lado)

   dobro <- (lado * lado) * 2
   
   escreva("O dobro da área do quadrado é:", dobro)

Fimalgoritmo