Algoritmo "maior valor"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Lê dois valores e escreve o maior deles.
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 12/05/2026
Var
   valor1: real
   valor2: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o primeiro valor: ")
   leia(valor1)
   escreva("Digite o segundo valor: ")
   leia(valor2)
   Se valor1 > valor2 entao
      escreval("O maior valor é: ", valor1:8:2)
   Senao
      escreval("O maior valor é: ", valor2:8:2)
   Fimse
Fimalgoritmo