Algoritmo "soma"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Solicita dois números, soma e exibe o resultado
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 12/04/2026
Var
// Seção de Declarações das variáveis 
numero1: inteiro
numero2: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o primeiro número: ")
   leia(numero1)
   escreva("Digite o segundo número: ")
   leia(numero2)
   resultado <- numero1 + numero2
   escreva("A soma dos números digitados é: ", resultado)

Fimalgoritmo