Algoritmo "sucessor"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Lê um número e calcular o sucessor.
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 12/04/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro
sucessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número: ")
   leia(numero)
   sucessor <- numero + 1
   escreva("O sucessor é: ", sucessor)

Fimalgoritmo