Algoritmo "verificar maior que 10"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Lê um valor e verifica se é maior que 10.
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 12/05/2026
Var
   valor: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(valor)
   Se valor > 10 entao
      escreval("É MAIOR QUE 10!")
   Senao
      escreval("NÃO É MAIOR QUE 10!")
   Fimse
Fimalgoritmo