Algoritmo "verificar positivo ou negativo"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Lê um valor e verifica se é positivo ou negativo,
// considerando zero como positivo.
// Autor(a)    : Gabriel dos Santos Ribeiro
// Data atual  : 12/05/2026
Var
   valor: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(valor)
   Se valor >= 0 entao
      escreval("O valor é POSITIVO!")
   Senao
      escreval("O valor é NEGATIVO!")
   Fimse
Fimalgoritmo